### ISSUE TITLE
checkpoints

### ISSUE THREAD

**Issue by Head** [paulkernfeld/burnie#7]
Hi,

one question: How do I know what checkpoints I can use?
Testnet height 153216 works, but 153217 say: 
Key not found in database [Tz84v/nJXRp3hyX01timiDORVJ5l5mRjqFoDAAAAAAA=]

**Comment by Head** [comment]
Got it. /2016

**Comment by paulkernfeld** [comment]
That's interesting. I would have expected non-multiples of 2016 to work, but to be a bit slower. Did this end up fixing the issue for you?

**Comment by Head** [comment]
Apart from that I don't exactly understand what's happening in the backend. But yes, It is working now for me.
Your project was needed to understand the bitcoin-spv/download stuff from @mappum :)
